// ============================================================================
// Client-Side Web Push Controller for PWA
// Pure W3C Web Push Protocol (Android, Windows, macOS, iOS 16.4+ PWA)
// ============================================================================

export function isPushSupported(): boolean {
  return (
    typeof window !== 'undefined' &&
    'serviceWorker' in navigator &&
    'PushManager' in window &&
    'Notification' in window
  )
}

export function isIosDevice(): boolean {
  if (typeof window === 'undefined') return false
  return /iPad|iPhone|iPod/.test(navigator.userAgent) && !(window as any).MSStream
}

export function isStandalonePwa(): boolean {
  if (typeof window === 'undefined') return false
  return (
    window.matchMedia('(display-mode: standalone)').matches ||
    Boolean((navigator as any).standalone)
  )
}

export function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4)
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/')
  const rawData = window.atob(base64)
  const outputArray = new Uint8Array(rawData.length)
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i)
  }
  return outputArray
}

export async function getExistingPushSubscription(): Promise<PushSubscription | null> {
  if (!isPushSupported()) return null
  try {
    const registration = await navigator.serviceWorker.ready
    return await registration.pushManager.getSubscription()
  } catch (err) {
    console.warn('[Push GetSubscription Warning]', err)
    return null
  }
}

export async function subscribeUserToPush(
  token: string
): Promise<{ success: boolean; error?: string }> {
  if (!isPushSupported()) {
    return { success: false, error: 'Push notifications are not supported on this browser' }
  }

  // iOS Safari Requirement: Must be installed as PWA on Home Screen (iOS 16.4+)
  if (isIosDevice() && !isStandalonePwa()) {
    return {
      success: false,
      error: 'On iPhones, you must first tap "Share" -> "Add to Home Screen" to enable lockscreen notifications.',
    }
  }

  try {
    const permission = await Notification.requestPermission()
    if (permission !== 'granted') {
      return { success: false, error: 'Notification permission was not granted' }
    }

    // 1. Fetch server's VAPID public key
    const res = await fetch('/api/push/vapid-public-key')
    if (!res.ok) {
      throw new Error('Failed to retrieve VAPID public key from server')
    }
    const { publicKey } = await res.json()
    const convertedVapidKey = urlBase64ToUint8Array(publicKey)

    // 2. Register with browser's native push service (Google FCM or Apple APNs)
    const registration = await navigator.serviceWorker.ready
    let subscription = await registration.pushManager.getSubscription()

    if (!subscription) {
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: convertedVapidKey,
      })
    }

    const subJson = subscription.toJSON()
    if (!subJson.endpoint || !subJson.keys?.p256dh || !subJson.keys?.auth) {
      throw new Error('Incomplete push subscription generated by browser')
    }

    // 3. Persist subscription to Cloudflare D1
    const saveRes = await fetch('/api/push/subscribe', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        endpoint: subJson.endpoint,
        keys: subJson.keys,
        userAgent: navigator.userAgent.slice(0, 150),
      }),
    })

    if (!saveRes.ok) {
      const errData = await saveRes.json().catch(() => ({}))
      throw new Error(errData.error || 'Failed to register subscription with server')
    }

    return { success: true }
  } catch (err: any) {
    console.error('[WebPush Subscribe Error]', err)
    return { success: false, error: err?.message || 'Failed to enable notifications' }
  }
}

export async function unsubscribeUserFromPush(token: string): Promise<boolean> {
  if (!isPushSupported()) return false
  try {
    const registration = await navigator.serviceWorker.ready
    const subscription = await registration.pushManager.getSubscription()
    if (subscription) {
      const endpoint = subscription.endpoint
      await subscription.unsubscribe()
      await fetch('/api/push/unsubscribe', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ endpoint }),
      }).catch(() => {})
    }
    return true
  } catch (err) {
    console.warn('[WebPush Unsubscribe Error]', err)
    return false
  }
}
